### ISSUE TITLE
The SDK doesn't support the "hosted_url" parameter returned in the response.

### ISSUE THREAD

**Issue by ima-tech** [berbix/berbix-node#10]
When creating a transaction, the documentation specifies we should be able to retrieve the 'hosted_url'. However, in the SDK, when calling the `createTransaction` method, it calls the `_fetchTokens` method and this method only returns a `Token` object. Therefore, we are unable to retrieve the `hosted_url`. The only way is to make the REST Api calls ourselves, which kind of defeats the purpose of having the SDK entirely.

See relevant code here (I suspect the fix would require quite a bit of a refactor):

```
Client.prototype._fetchTokens = async function (path, payload) {
  var headers = {
    Authorization:
      "Basic " + new Buffer.from(`${this.apiSecret}:`).toString("base64"),
    "User-Agent": "BerbixNode/" + SDK_VERSION,
  };
  var result = await this._request("POST", path, headers, payload);
  return new Tokens(
    result.refresh_token,
    result.access_token,
    result.client_token,
    now() + result.expires_in,
    result.transaction_id,
    result
  );
};

Client.prototype.createTransaction = function (opts) {
  var payload = {};
  if (opts.email != null) {
    payload.email = opts.email;
  }
  if (opts.phone != null) {
    payload.phone = opts.phone;
  }
  if (opts.customerUid != null) {
    payload.customer_uid = "" + opts.customerUid;
  }
  if (opts.templateKey != null) {
    payload.template_key = opts.templateKey;
  }
  if (opts.hostedOptions != null) {
    var hostedOptions = {};
    if (opts.hostedOptions.completionEmail != null) {
      hostedOptions.completion_email = opts.hostedOptions.completionEmail;
    }
    if (opts.hostedOptions.redirectUrl != null) {
      hostedOptions.redirect_url = opts.hostedOptions.redirectUrl;
    }
    payload.hosted_options = hostedOptions;
  }
  return this._fetchTokens("/v0/transactions", payload);
};
```

**Comment by jnnnthnn** [comment]
Thank you for the bug report, @ima-tech!

We're currently working on release a v.1.0.0 version of our API libraries which will enable proper handling of the `hosted_url` return value. Would you have a sense of when you'd ideally need this to move forward with your integration without having to directly integrate against our API? Feel free to respond at support@berbix.com if you'd prefer to take things offline.

**Comment by ima-tech** [comment]
Oh I already integrated against your API but just wanted to let you know in case you weren't aware.

**Comment by jnnnthnn** [comment]
> Oh I already integrated against your API but just wanted to let you know in case you weren't aware.

Got it! Thank you so much, and apologies for making your integration harder to complete.
